### ISSUE TITLE
EqualityComparison used with ReverseMap causes InvalidOperationException

### ISSUE THREAD

**Issue by mgauthierUnicel** [AutoMapper/AutoMapper.Collection#109]
It would be of great use to add to the documentation that you have to call EqualityComparison on each side of the ReverseMap method when creating a manual map

ex:
`cfg.CreateMap<OrderItemDTO, OrderItem>()
	.EqualityComparison((odto, o) => odto.ID == o.ID)
	.ReverseMap();`
will fail with an unmeaningful InvalidOperationException Sequence does not contain any element deep into the library forcing to walk into the code to understand what causes the issue

Result StackTrace:	
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AutoMapper.EquivalencyExpression.ExpressionExtentions.<>c__DisplayClass1_0.<GetSinglePredicateExpressionArgumentType>b__0(Type t) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection\EquivalencyExpression\ExpressionExtentions.cs:line 23
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.EquivalencyExpression.ExpressionExtentions.GetSinglePredicateExpressionArgumentType(Type type) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection\EquivalencyExpression\ExpressionExtentions.cs:line 17
   at AutoMapper.Mappers.ObjectToEquivalencyExpressionByEquivalencyExistingMapper.IsMatch(TypePair typePair) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection\Mappers\ObjectToEquivalencyExpressionByEquivalencyExistingMapper.cs:line 23
   at AutoMapper.MapperConfiguration.<>c__DisplayClass70_0.<FindMapper>b__0(IObjectMapper m) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 425
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.MapperConfiguration.FindMapper(TypePair types) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 425
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 227
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1() in C:\projects\automapper\src\AutoMapper\LockingConcurrentDictionary.cs:line 15
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 212
   at AutoMapper.MapperConfiguration.ResolveTypeMap(Type sourceType, Type destinationType) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 197
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection\EquivalencyExpression\EquivalentExpressions.cs:line 54
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection\Mappers\EquivalentExpressionAddRemoveCollectionMapper.cs:line 69
   at AutoMapper.MapperConfiguration.<>c__DisplayClass70_0.<FindMapper>b__0(IObjectMapper m) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 425
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.MapperConfiguration.FindMapper(TypePair types) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 425
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 227
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1() in C:\projects\automapper\src\AutoMapper\LockingConcurrentDictionary.cs:line 15
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 212
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 208
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolveTypeMap|6(TypePair types) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 150
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolvePropertyTypeMap|5(PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 142
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>b__1(PropertyMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 96
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 99
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 58
   at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 293
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 284
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 219
   at AutoMapper.MapperConfiguration.BuildExecutionPlan(MapRequest mapRequest) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 120
   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 110
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1() in C:\projects\automapper\src\AutoMapper\LockingConcurrentDictionary.cs:line 15
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 108
   at AutoMapper.Mapper.AutoMapper.IMapper.Map(Object source, Type sourceType, Type destinationType) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 300
   at AutoMapper.EntityFramework.Persistence`1.InsertOrUpdate(Type type, Object from) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection.EntityFramework\Persistence.cs:line 28
   at AutoMapper.EntityFramework.Persistence`1.InsertOrUpdate[TFrom](TFrom from) in C:\Users\production2\Downloads\AutoMapper.Collection-master\src\AutoMapper.Collection.EntityFramework\Persistence.cs:line 23

**Comment by penfold** [comment]
> It would be of great use to add to the documentation that you have to call EqualityComparison on each side of the ReverseMap method when creating a manual map

Is it still the case that EqualityComparison is needed to be added to both sides of the map?

Even when using ReverseMap?

Thanks,
Paul

**Comment by Tasteful** [comment]
From version 6 the reverse map will also add the equality comparison expression.

**Comment by penfold** [comment]
Therefore, if the forward and reverse mappings were created without using ReverseMap, then I would need to add both the forward and reverse equality comparison expressions? (As the mappings are defined independently of each other.)

**Comment by Tasteful** [comment]
@penfold yes, if you not using the `.ReverseMap()`, then you need to add multiple equality comparison expressions.
