### ISSUE TITLE
Add support for AutoMapper 11.0.0

### ISSUE THREAD

**Issue by wojtek-abakus** [AutoMapper/AutoMapper.Collection#162]
After upgrading to AutoMapper 11 method AddCollectionMappers ends with exception

`System.TypeLoadException: Could not load type 'AutoMapper.IObjectMapper' from assembly 'AutoMapper, Version=11.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'.
   at Mappings.Framework.IoC.MappingsModule.<>c__DisplayClass0_0.<Load>b__2(IMapperConfigurationExpression config)
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Mappings.Framework.IoC.MappingsModule.<>c.<Load>b__0_0(IComponentContext context)
   at Autofac.RegistrationExtensions.<>c__DisplayClass41_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)`

**Comment by vpetrusevici** [comment]
Hello @AutoMapper 
Is this lib still supported?

**Comment by replaysMike** [comment]
apparently not

**Comment by Victor-Nyagudi** [comment]
Does AutoMapper.Collection work with previous versions of AutoMapper? If so, which ones?

**Comment by vpetrusevici** [comment]
> Does AutoMapper.Collection work with previous versions of AutoMapper? If so, which ones?

10.x.x

**Comment by shidcordero** [comment]
Any update on this? also waiting for this progress as Automapper 11.0 version was the only version that worked for HotChocolate Optional types.

**Comment by lbargaoanu** [comment]
Fixed by #164.
