### ISSUE TITLE
GenerateEntityFrameworkPrimaryKeyPropertyMaps throws null pointer exception (v6.0.0)

### ISSUE THREAD

**Issue by penfold** [AutoMapper/AutoMapper.Collection#37]
I've updated my project to v6 and made changes for the new syntax. But I'm getting a null pointer exception:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'

My code is:
```
 Mapper.Initialize(configuration =>
                {
                    configuration.AddProfile(new AutoMapperProfile());
                    configuration.AddCollectionMappers();
                    configuration.SetGeneratePropertyMaps<GenerateEntityFrameworkPrimaryKeyPropertyMaps<ApplicationDbContext>>();
                });

```

The stacktrace is:
```
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c.<CreateEquivalentExpression>b__11_0(PropertyMap pm)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.CreateEquivalentExpression(IEnumerable`1 propertyMaps)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass7_0.<GetEquivalentExpression>b__1(IGeneratePropertyMaps _)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass7_0.<GetEquivalentExpression>b__0(TypePair tp)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationProvider configurationProvider, TypeMap typeMap)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair)
   at AutoMapper.MapperConfiguration.<>c__DisplayClass54_0.<CoveredByObjectMap>b__0(IObjectMapper m)
   at AutoMapper.MapperConfiguration.CoveredByObjectMap(TypePair typePair)
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at XXXXXX.UnityConfig.ConfigureAutoMapper(IUnityContainer container) in XXXXXX\App_Start\UnityConfig.cs:line 78
   at XXXXXX.UnityConfig.RegisterTypes(IUnityContainer container) in XXXXXX\App_Start\UnityConfig.cs:line 73
   at XXXXXX.UnityConfig.<>c.<.cctor>b__5_0() in XXXXXX\App_Start\UnityConfig.cs:line 29
   at System.Lazy`1.CreateValue()
```

Any hints on what I'm doing wrong?

**Comment by TylerCarlson1** [comment]
Most likely you don't have all the Keys mapped to the DTO from the Entity class and it can't find a matching property map for the key and this exception is what you get.  It uses all keys so make sure you have those properties with matching name on the DTO, or have them mapped explicitly.

The exception doesn't tell you which one it is, you'll have to go look at all your mappings to see if Keys are matched.

If you don't have the keys in the DTO it doesn't know how to check if 2 items are equivalent to one another.
