### ISSUE TITLE
Exception thrown with custom GetHashCode() implementation on Value Objects.

### ISSUE THREAD

**Issue by kellermanrivero** [AutoMapper/AutoMapper.Collection#54]
Hi, 
I have been experiencing errors trying to create a map between an inmutable object value and an entity. 

# Charge Inmutable Object
```
public class Charge
    {  
        public Charge(string category, string description, decimal value)
        {
            Category = category;
            Description = description;
            Value = value;
        }

        public string Category { get; }
        public string Description { get; }
        public decimal Value { get; }

        public override string ToString()
        {
            return $"{Category}|{Description}|{Value}";
        }

        public override int GetHashCode()
        {
            return $"{Category}|{Description}|{Value}".GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            var _obj = obj as Charge;

            if (_obj == null)
            {
                return false;
            }

            return Category == _obj.Category && Description == _obj.Description && Value == _obj.Value;
        }
    }
```

# Entity

```
public class SaleCharge
    {
        public Guid SaleId { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public decimal Value { get; set; }

        public virtual Sale Sale { get; set; }                
    }
```

# Mappings

```
CreateMap<Charge, SaleCharge>()
                .ForMember(d => d.Sale, o => o.Ignore())
                .ForMember(d => d.SaleId, o => o.Ignore())
                .EqualityComparison((c, sc) => sc.Category == c.Category && sc.Description == c.Description);

            CreateMap<SaleCharge, Charge>()
                .ConstructUsing(
                    (saleCharge => new Charge(saleCharge.Category, saleCharge.Description, saleCharge.Value)))
                .EqualityComparison((sc, c) => sc.Category == c.Category && sc.Description == c.Description);    
```

# Runtime Error

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Method 'Int32 GetHashCode()' declared on type 'Leaderboard.Sales.Charge' cannot be called with instance of type 'System.String'
   at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateMethodAndGetParameters(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method)
   at AutoMapper.EquivalencyExpression.ExpressionExtentions.GetHashCodeExpression[T](List`1 members, ParameterExpression sourceParam)
   at AutoMapper.EquivalencyExpression.EquivalentExpression`2..ctor(Expression`1 equivalentExpression)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.EqualityComparison[TSource,TDestination](IMappingExpression`2 mappingExpression, Expression`1 EquivalentExpression)
   at Leaderboard.Sales.API.Mappings.DefaultProfile..ctor() in /home/kellerman/Repos/Leaderboard 2/Services/Sales/Leaderboard.Sales.API/Mappings/DefaultProfile.cs:line 23
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at AutoMapper.Configuration.MapperConfigurationExpression.AddProfile(Type profileType)
   at AutoMapper.ServiceCollectionExtensions.<>c__DisplayClass16_0.<AddAutoMapperClasses>b__4(IMapperConfigurationExpression cfg)
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 additionalInitAction)
   at Leaderboard.Sales.API.Startup.ConfigureServices(IServiceCollection services) in /home/kellerman/Repos/Leaderboard 2/Services/Sales/Leaderboard.Sales.API/Startup.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Leaderboard.Sales.API.Program.Main(String[] args) in /home/kellerman/Repos/Leaderboard 2/Services/Sales/Leaderboard.Sales.API/Program.cs:line 14
```

If I remove the GetHashCode on Charge value object then I got not error at all. But I think this is a bug, so I'm filling the issue. 

Thank you.

**Comment by TylerCarlson1** [comment]
Fix is on the MyGet feed as a pre-release version.  https://www.myget.org/F/automapperdev/api/v2

**Comment by niemyjski** [comment]
I also ran into this with the following code: `CreateMap<ViewField, Field>().EqualityComparison((src, dest) => src.Id == dest.Id);`

```
at lambda_method(Closure , ViewFieldDefinition )
   at AutoMapper.EquivalencyExpression.EquivalentExpression`2.GetHashCode(Object obj)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.<>c__DisplayClass5_0`4.<Map>b__3(TSourceItem x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
```
It appears that it was doing a GetHashCode on the src.id which was null. This was working in 3.0.1 (broken after updating to 3.1.1)

**Comment by TylerCarlson1** [comment]
@niemyjski Does the version on MyGet fix your issue?  It's 3.1.2 pre-release

**Comment by niemyjski** [comment]
I didn't try it, I just changed it to String.Equals

**Comment by yacobcz** [comment]
I can confirm that 3.1.2 pre-release fixes following bug for me:

`Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Method 'Int32 GetHashCode()' declared on type 'Entity' cannot be called with instance of type 'System.Int32'
`
