### ISSUE TITLE
EquivalentExpressions.EquivalentExpressionDictionary is not thread safe

### ISSUE THREAD

**Issue by nphmuller** [AutoMapper/AutoMapper.Collection#77]
On AutoMapper.Collection 3.1.3

During my test code I initialize multiple AutoMapper instances. Since my tests run in parellel, the creation of a new Mapper instance should be thread-safe, which it is. (Probably since the static API was deprecated).

Now, since I added AutoMapper.Collection my tests fail with the following exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass5_0`1.<InsertBefore>b__1(IConfigurationProvider c)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at MyApp.CreateAutoMapper()
```
   
After a bit of digging it turns out that `EquivalentExpressions.AddCollectionMappers()` is not thread safe, because the static dictionary `EquivalentExpressionDictionary` is not.

The issue is easily reproducable with the following test:

``` c#
[Fact]
public void ConfigShouldBeThreadSafe()
{
    Action act = () =>
    {
        new AutoMapper.MapperConfiguration(cfg =>
        {
            cfg.AddCollectionMappers();
        });
    };
    var tasks = new List<Task>();
    for (var i = 0; i < 5; i++)
    {
        tasks.Add(Task.Run(act));
    }

    Task.WaitAll(tasks.ToArray());
}
```

**Comment by nphmuller** [comment]
I haven't been able to let the same test as above fail in `Automapper.Collection.Tests` yet, so I made a repro.
Simply run `dotnet test` after checkout to see the test fail. Based on the `dotnet new xunit` template.

**Comment by cdibbs** [comment]
Ohh please, ohh pleeease release 3.1.4. TeamCity haaaates me, right now!! :-) Thanks for your work on this, guys.

**Comment by cdibbs** [comment]
@TylerCarlson1 Any idea when 3.1.4 might release? I'm working on an app that relies heavily on parallelization, and I'm hoping not to have to implement any workarounds before going to production. Thanks!

**Comment by TylerCarlson1** [comment]
I want the other issues to be fixed but others aren't responding.  If you really need you need it now you can add the [MyGet](https://www.myget.org/F/automapperdev/api/v2) feed and use the continuous integration builds which will have this fix.
