### ISSUE TITLE
Update to AM 6.2.2 from 5.5.0 gives exception: ValueFactory attempted to access the Value property of this instance.

### ISSUE THREAD

**Issue by chiefley** [AutoMapper/AutoMapper.Collection#80]
During startup we run a routine that looks through the assemblies to find what it should map.  Everything has run fine for the last 6 months.  On upgrade to 6.2.2, I added the new way of initializing am.collection, but it blows up with the "Value attempted...." error.

I have looked through all the issues that seem to be related to this but nothing stands out as a cure for my particular case.  Here is my code.

	public static class AutomapperConfigurator
	{
		public static void LoadMapsFromCallerAndReferencedAssemblies(Func<AssemblyName, bool> assemblyFilter = null)
		{
			var target = Assembly.GetCallingAssembly();

			Func<AssemblyName, bool> loadAllFilter = (x => true);

			var assembliesToLoad = target.GetReferencedAssemblies()
				.Where(assemblyFilter ?? loadAllFilter)
				.Select(a => Assembly.Load(a))
				.ToList();

			assembliesToLoad.Add(target);

			LoadMapsFromAssemblies(assembliesToLoad.ToArray());
		}
		public static void LoadMapsFromAssemblies(params Assembly[] assemblies)
		{
			var types = assemblies.SelectMany(a => a.GetExportedTypes()).ToArray();

		       Mapper.Initialize(cfg =>
			{
                             // Add this line to initialize am.collections v3 with AM 6.2.2
                              cfg.AddCollectionMappers();
                              Load(cfg, types);
                       });
		}
		private static void Load(IMapperConfigurationExpression cfg, Type[] types)
		{
			LoadIMapFromMappings(cfg, types);
			LoadIMapToMappings(cfg, types);
			LoadCustomMappings(cfg, types);

                      // Commented out for the update to newer Automapper package.  DMC
                     //  cfg.AddProfile<CollectionProfile>();
		}

Other info:  This is .Net 4.6.1.  AM.Collection is v3.1.3.   The above code is called during Startup of the WebApi hosted in Owin.

Thanks in advance.

**Comment by TylerCarlson1** [comment]
A repro would help. Make a gist that we can execute and see fail.

Only other things I can see is that AddCollectionMappers is called before other mappings instead of after like in the old code.

Other thing is are you calling `LoadMapsFromCallerAndReferencedAssemblies` and `LoadMapsFromAssemblies`?  Both are public and will initialize a new static instance.  If you are calling both or one more than once that might be what's causing the problem.

**Comment by chiefley** [comment]
Thanks for the reply.  I tried moving the AddCollectionMappers before or after the Load method.  I get the same results.

Good point on the two public methods.  I am only calling one LoadMapsFromCallerAndReferenceAssemblies from my startup code.  But I will make the other one private and see if there is anything calling it.

**Comment by chiefley** [comment]
Ok, wouldn't you know, the small repro I made works fine.  I guess I have some work to do in trying to reproduce the problem in a simpler setting.

**Comment by chiefley** [comment]
I wasn't able to reproduce the problem in my small repro.  But in the actual application, the exception does not occur in the cfg.AddCollectionMappers(); line.   It occurs after some maps are registered.  

It does not occur if only the first line of mapping (LoadIMapFromMappings(cfg, types);) is present (the rest are commented out).

**Comment by TylerCarlson1** [comment]
Maybe it has something to do with the registering.  Are any of your mappings calling Mapper.Map or have an instance of IMapper to map inside of the registration of the configuration?

**Comment by psyren89** [comment]
I am also having this issue in a .NET Core 2.1 app - the exception seems to be thrown after `services.AddAutoMapper(config => config.AddCollectionMappers())` completes. There is no issue if `config => config.AddCollectionMappers()` is removed.

Here is a stacktrace:
```
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 212
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 208
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolveTypeMap|6(TypePair types) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 150
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolvePropertyTypeMap|5(PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 142
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>b__1(PropertyMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 96
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 99
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 60
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 284
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 219
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 208
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolveTypeMap|6(TypePair types) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 150
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolvePropertyTypeMap|5(PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 142
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>b__1(PropertyMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 96
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 99
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 60
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 284
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 219
   at AutoMapper.MapperConfiguration.ResolveTypeMap(Type sourceType, Type destinationType) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 197
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair)
   at AutoMapper.MapperConfiguration.<>c__DisplayClass70_0.<FindMapper>b__0(IObjectMapper m) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 425
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at AutoMapper.MapperConfiguration.FindMapper(TypePair types) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 425
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 227
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1() in C:\projects\automapper\src\AutoMapper\LockingConcurrentDictionary.cs:line 15
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 212
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 208
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolveTypeMap|6(TypePair types) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 150
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolvePropertyTypeMap|5(PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 142
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>b__1(PropertyMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 96
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 99
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 60
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 284
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 219
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 208
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolveTypeMap|6(TypePair types) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 150
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__ResolvePropertyTypeMap|5(PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 142
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>b__1(PropertyMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 96
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 99
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 60
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 284
   at AutoMapper.MapperConfiguration.Seal() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 348
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 53
   at AutoMapper.Mapper.Initialize(Action`1 config) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 42
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
   at XXX.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Work\XXX\XXX.Web\Startup.cs:line 82
```

**Comment by psyren89** [comment]
Turns out this was actually due to a mismatching type somewhere. My problem has been resolved.

**Comment by MaryadaPurshottam** [comment]
psyren89, can you elaborate on your solution, what you did? I'm having the same issue you described (albeit for the EfCore version of this). When i add AddCollectionMappers() is when this error gets thrown. 
Thanks

**Comment by psyren89** [comment]
It was due to the wrong `using` for a particular type - check the mapping configuration uses the correct type, but also check where the mapper is called.
